### ISSUE TITLE
App is crashed after pinch to zoom or move the model while reading arfican_statues.stl

### ISSUE THREAD

**Issue by ToanNV** [andresoviedo/android-3D-model-viewer#50] opened 2018-06-07 02:57 UTC
1. Open african_statue.stl
2. Move the object or pinch to zoom

App is crashed. Please fix asap

**Comment by andresoviedo** [comment] 2018-08-21 11:09
Thanks for the feedback.

Duplicate of #39

**Closed by andresoviedo** 2018-08-21 11:09 UTC
Labels: bug, duplicate
