### ISSUE TITLE
Performance problems with high vertex shapes

### ISSUE THREAD

**Issue by jamesbellaero** [andresoviedo/android-3D-model-viewer#1] opened 2016-06-22 22:29 UTC
The rendering time for objects such as the truck (or objects I'm trying to render) is around 5 seconds or higher per frame. I'm not very familiar with your code or rendering algorithm yet, but if you have any ideas of how to speed things up let me know.

**Comment by andresoviedo** [comment] 2016-06-28 22:21
Hi James. That's basically freezed  Did you try disabling lights & textures?  Does it happens with any other demo model? Please, what android device do you have?

**Comment by jamesbellaero** [comment] 2016-06-29 14:09
I'm using a Nexus 6, and it seems to happen with any models with large
files. I disabled lights and textures but it's still pretty slow. Is there
a way to multithread drawing with OpenGL? I wouldn't mind working on that
if you know of one.

**Comment by andresoviedo** [comment] 2016-07-18 15:41
Hi James. I'm sorry because I was not able to get a Nexus 6 to test it. As far as I understand, multithreading with OpenGL is not possible. So I am afraid I don't know how to help you on this. Probably if you look at the logs with the command "adb logcat" would probably print some info that may help us debug the issue. If that doesn't help, probably profling the app (I am not expert on this) would probably help us pin pointing where the hot spots are. If I can help you in either way please tell me.

**Comment by andresoviedo** [comment] 2016-10-13 18:26
Hi @jamesbellaero Do you still have this issue?  If you do, please debug it with `adb logcat` so we can see what's happening. If the issue is solved tell me so I can close it. Kind regards

**Closed** 2017-03-26 23:08 UTC
Labels: bug
