### ISSUE TITLE
Bug with textures

### ISSUE THREAD

**Issue by olegVovkZazmic** [andresoviedo/android-3D-model-viewer#32] opened 2018-01-03 18:24 UTC
Click Load Model Item --> choose file .obj. In this folder with file .obj file .mtl exist. During building model I see error in logcat.
`01-03 20:18:13.896 26400-27307/? E/GLUtil: Error compiling program: --From Vertex Shader:
                                           Error: uniform variables in vertex shader do not fit in 256 vectors.
                                           --From Fragment Shader:
                                           Error: uniform variables in vertex shader do not fit in 256 vectors.
01-03 20:18:13.901 26400-27307/? E/ModelRenderer: There was a problem rendering the object 'figurine_27201KM.obj':Error creating program.
                                                  java.lang.RuntimeException: Error creating program.
                                                      at org.andresoviedo.app.model3D.util.GLUtil.createAndLinkProgram(GLUtil.java:65)
                                                      at org.andresoviedo.app.model3D.model.Object3DImpl.<init>(Object3DImpl.java:45)
                                                      at org.andresoviedo.app.model3D.model.Object3DV9.<init>(Object3DImpl.java:995)
                                                      at org.andresoviedo.app.model3D.model.Object3DBuilder.getDrawer(Object3DBuilder.java:426)
                                                      at org.andresoviedo.app.model3D.view.ModelRenderer.onDrawFrame(ModelRenderer.java:175)
                                                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
                                                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`
And after building my 3d model without textures

Please help! Thanks

**Comment by andresoviedo** [comment] 2018-01-11 19:03
I had never seen this error before. 
As a workaround I can suggest you to comment the following line [Object3DBuilder.java:430](https://github.com/andresoviedo/android-3D-model-viewer/blob/master/app/src/main/java/org/andresoviedo/app/model3D/model/Object3DBuilder.java#L430) so you can load your obj while I investigate what's your issue. 

What android version do you have?

**Comment by olegVovkZazmic** [comment] 2018-01-12 10:10
Android version on my device 6.0. I download 3d model in my Google disk, just try open it with your app and your definitely catch this bug.
[https://drive.google.com/file/d/1MUcjTwOnxGJUrlPYHE7kegrQPUfINpB3/view?usp=sharing](url)

**Comment by andresoviedo** [comment] 2018-01-12 19:34
The problem is not with your model, as it is exploding compiling the shader for rendering DAE files.
Can you confirm that the app is exploding also with the included models?

**Comment by olegVovkZazmic** [comment] 2018-01-16 11:02
With existing models which in resources all ok. Problem only with models like that which I uploaded on google disk.

**Comment by olegVovkZazmic** [comment] 2018-01-22 17:07
**I tried to download a similar model and catch this**

01-22 18:54:38.799 29133-29750/com.example.alytar.bobbled E/GLUtil: Could not compile program:  | const int MAX_JOINTS = 200;
                                                                    const int MAX_WEIGHTS = 3;
                                                                    uniform mat4 u_MVPMatrix;      
                                                                    attribute vec4 a_Position;     
                                                                    attribute vec3 in_jointIndices;
                                                                    attribute vec3 in_weights;
                                                                    uniform mat4 jointTransforms[MAX_JOINTS];
                                                                    uniform mat4 u_MVMatrix;
                                                                    uniform vec3 u_LightPos;
                                                                    attribute vec3 a_Normal;
                                                                    uniform vec4 vColor;
                                                                    varying vec4 v_Color;
                                                                    attribute vec2 a_TexCoordinate;varying vec2 v_TexCoordinate;void main()                    
                                                                    {                              
                                                                      vec4 totalLocalPos = vec4(0.0);
                                                                      vec4 totalNormal = vec4(0.0);
                                                                        mat4 jointTransform = jointTransforms[int(in_jointIndices[0])];
                                                                        vec4 posePosition = jointTransform * a_Position;
                                                                        totalLocalPos += posePosition * in_weights[0];
                                                                        jointTransform = jointTransforms[int(in_jointIndices[1])];
                                                                        posePosition = jointTransform * a_Position;
                                                                        totalLocalPos += posePosition * in_weights[1];
                                                                        jointTransform = jointTransforms[int(in_jointIndices[2])];
                                                                        posePosition = jointTransform * a_Position;
                                                                        totalLocalPos += posePosition * in_weights[2];
                                                                      gl_Position = u_MVPMatrix * totalLocalPos;
                                                                      gl_PointSize = 2.5;         
                                                                       vec3 modelViewVertex = vec3(u_MVMatrix * a_Position);
                                                                                 vec3 lightVector = normalize(u_LightPos - modelViewVertex);
                                                                           vec3 modelViewNormal = vec3(u_MVMatrix * vec4(a_Normal, 0.0));
                                                                        float diffuse = max(dot(modelViewNormal, lightVector), 0.1);
                                                                          float distance = length(u_LightPos - modelViewVertex);
                                                                                diffuse = diffuse * (1.0 / (1.0 + (0.05 * distance * distance)));
                                                                      diffuse = diffuse + 0.5;   v_Color = vColor * diffuse;
                                                                       v_Color[3] = vColor[3];  v_TexCoordinate = a_TexCoordinate;}                              
01-22 18:54:38.802 29133-29750/com.example.alytar.bobbled E/GLUtil: Error compiling program: L0100 GLSL allows exactly two attached shaders (one of each type) per program
01-22 18:54:38.810 29133-29750/com.example.alytar.bobbled E/ModelRenderer: There was a problem rendering the object 'figurine_ABCDEFG.obj':Error creating program.
                                                                           java.lang.RuntimeException: Error creating program.
                                                                               at com.example.alytar.bobbled.ui.activity.show3dModel.show3dModelUtil.util.GLUtil.createAndLinkProgram(GLUtil.java:65)
                                                                               at com.example.alytar.bobbled.ui.activity.show3dModel.show3dModelUtil.Object3DImpl.<init>(Object3DImpl.java:45)
                                                                               at com.example.alytar.bobbled.ui.activity.show3dModel.show3dModelUtil.Object3DV9.<init>(Object3DImpl.java:963)
                                                                               at com.example.alytar.bobbled.ui.activity.show3dModel.show3dModelUtil.Object3DBuilder.getDrawer(Object3DBuilder.java:427)
                                                                               at com.example.alytar.bobbled.ui.activity.show3dModel.show3dModelUtil.model.ModelRenderer.onDrawFrame(ModelRenderer.java:174)
                                                                               at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
                                                                               at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

 
**Honestly, I don't understand how to fix this, and how make it that the file .mtl was read. I find that _Object3DData.class / byte[] textureData = null all time._**

**Comment by yanayh90** [comment] 2018-06-26 07:50
I Use my obj and dae and also byte[] textureData is null all time,
When the examples works great.

**Comment by andresoviedo** [comment] 2018-09-08 22:42
Fixed in lastest version. Tested on my phone. If it's not ok for you, reopen issue.

**Closed by andresoviedo** 2018-09-08 22:42 UTC
Labels: bug
